spring:
  profiles:
    include:
      - eureka_client
      - common
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eugmall?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath*:mappers/*Mapper.xml
  typeAliasesPackage: com.eugene.sumarry.mall.user.model
  typeHandlersPackage: com.eugene.sumarry.mall.user.dao.typehandler
  configuration:
    cacheEnabled: true
server:
  port: 5000


